[package]
name = "plonk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5"
ark-ec = "0.5"
ark-poly = "0.5"
ark-bls12-381 = "0.5"
ark-serialize = "0.5"
ark-std = "0.5"
sha2 = "0.10"
rand = "0.8"

[dev-dependencies]
rand_chacha = "0.3"
criterion = "0.5"

[[bench]]
name = "prove"
harness = false

[profile.release]
debug = true
